version: "3.9"
services:
  monguito:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: esperanto
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  app:
    build:
      context: .
    depends_on:
      - monguito
    ports:
      - "3000:3000"
